# -------- dependencies --------
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# -------- build --------
FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build --turbopack

# -------- runtime --------
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# copia solo lo necesario para ejecutar standalone
COPY --from=builder /app/.next/standalone ./

# Puerto interno (puedes dejarlo en 3000, o cambiarlo si prefieres)
EXPOSE 3000

# Ejecuta el server standalone generado por Next
CMD ["node", "server.js"]
