# Project Key
sonar.projectKey=proyecto-test2

# Nombre del proyecto (tag)
sonar.projectName=proyecto-test2 Local 
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/build/**, **/coverage/**, **/Diagramas/**, **/*.png, **/*.jpg, **/*.jpeg

sonar.host.url=http://localhost:9000/

# Token de seguridad
sonar.login=sqp_2620d272c53cafdd186b893e3005a32c24cdac75
# Carpetas y qué archivos revisará TypeScript
sonar.typescript.tsconfigPaths=tsconfig.sonar.json