networks:
  totem_network_static:
    driver: bridge



services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=test123
      - path.repo=/snapshots # define esto en tu .env
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./database/backup/es_snapshots:/snapshots 
    networks:
      - totem_network_static
    container_name: database-es01-1
volumes:
  esdata:

