services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=test123
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=${KIBANA_SA_TOKEN}
      - NODE_OPTIONS=--max-old-space-size=1024
    ports:
      - "5601:5601"
    depends_on:
      - es01
volumes:
  esdata:
